apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-node-mongo
  labels:
    app: docker-node-mongo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: docker-node-mongo
  template:
    metadata:
      labels:
        app: docker-node-mongo
    spec:
      containers:
      - name: docker-node-mongo
        image: teperwoman/mongo-app
        ports:
        - containerPort: 3000