apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-node-mongo
  labels:
    app: docker-node-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-node-mongo
  template:
    metadata:
      labels:
        app: docker-node-mongo
    spec:
      containers:
      - name: docker-node-mongo
        image: tftest/mongo-app
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: docker-node-mongo
spec:
  selector:
    app: docker-node-mongo
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000