kind: Namespace
apiVersion: v1
metadata:
  name: docker-node-mongo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-node-mongo
  labels:
    app: docker-node-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-node-mongo
  template:
    metadata:
      labels:
        app: docker-node-mongo
    spec:
      containers:
      - name: docker-node-mongo
        image: tftest/mongo-app
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: docker-node-mongo
spec:
  selector:
    app: docker-node-mongo
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: ingress-test-apache-php
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  tls:
    - hosts:
        - docker.node-mongo.com
  rules:
    - host: docker.node-mongo.com
      http:
        paths:
          - path: /(.*)
            backend:
              serviceName: docker-node-mongo
              servicePort: 3000